---
- name: Upgrade cluster nodes.
  hosts: cluster
  gather_facts: true
  become: true

  tasks:
    - name: Upgrade software.
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Check for reboot.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: reboot_required_file

    - name: Reboot node.
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove old dependencies.
      ansible.builtin.apt:
        autoremove: true
